#!/usr/bin/perl

# Copyright (C) Matevz Tadel.
# This file is part of Gled.
# SPDX-License-Identifier: LGPL-3.0-or-later

use lib "$ENV{GLEDSYS}/perllib";
use Gled_ConfCat_Parser;

# Writes the make rules of a libset's dictionary (make_dict.inc).
# Usage: gled_mk_dict_dep.pl <libsetname> <headers ...>

# read build config
Gled_ConfCat_Parser::import_build_config();
Gled_ConfCat_Parser::parse_catalog();

$libset = shift;

print "# Generated by gled_mk_dict_dep.pl for libset $libset; do not edit. Make\n" .
      "# rewrites it when glass.list, a LinkDef.h or the Makefile changes.\n\n";

exit 0 unless @ARGV;

for $h (@ARGV) {
  ($d) = $h =~ m!^(\w+)/! or die "header '$h' not in a directory";
  push @dirs, $d unless exists $dir_hdrs{$d};
  push @{$dir_hdrs{$d}}, $h;
}
for $c (@{$CATALOG->{ClassList}}) {
  ($d) = $CATALOG->{Classes}{$c}{Stem} =~ m!^(\w+)/!;
  $glass_dirs{$d} = 1;
}

for $d (@dirs) {
  die "$libset: dictionary headers in $d/, but no glasses and no $d/LinkDef.h\n"
    unless $glass_dirs{$d} or -r "$d/LinkDef.h";
}

$name  = "${libset}_Dict";
$deps  = join(" ", map { "\$(wildcard $_/LinkDef.h)" } @dirs) .
         (%glass_dirs ? " glass.list" : "");
$hdrs  = join(" ", @ARGV);
$dbase = "$config->{DICT_DIR}/$name";
print "$dbase.d: $hdrs\n";
print "\t\${ECHO} -d- Mk-dict-depend $name\n";
print "\t\${MUTE} \${MKDEP} \${MKDEPFLAGS} -- \${LOCALINCL} -- \$^ -f- 2>/dev/null | " .
          "sed -e 's!^[^ :]*\\.o:!$dbase.cc:!' > \$\@\n";
print "$dbase.cc: $hdrs $deps\n";
print "\t\${ECHO} -=- Rootcling $name\n";
print "\t\${MUTE} (CPPFLAGS=\"\${CPPFLAGS}\" \${MKDICTGEN} $libset $hdrs)\n";
