#!/usr/bin/perl

# Copyright (C) Matevz Tadel.
# This file is part of Gled.
# SPDX-License-Identifier: LGPL-3.0-or-later

# Generates the dictionary of a libset as a C++ module, with one rootcling run.
# Usage, in the libset directory: gled_mk_dict_gen.pl <libsetname> <headers ...>

use lib "$ENV{GLEDSYS}/perllib";
use Carp;
use Gled_ConfCat_Parser;

Gled_ConfCat_Parser::import_build_config();
Gled_ConfCat_Parser::parse_catalog();

my $libset = shift;
my @hdrs   = @ARGV;
my $dict   = $config->{DICT_DIR};
my $specs  = $resolver->{LibName2LibSpecs};

#-------------------------------------------------------------------------------
# Selection rules
#-------------------------------------------------------------------------------

my (%dir_hdrs, @dirs);
for my $h (@hdrs)
{
  my ($d) = $h =~ m!^(\w+)/! or croak "header '$h' not in a directory";
  push @dirs, $d unless exists $dir_hdrs{$d};
  push @{$dir_hdrs{$d}}, $h;
}

my $rules = "";
for my $dir (@dirs)
{
  my $user_file  = "${dir}/LinkDef.h";
  my $user_rules = "";
  if (-r $user_file)
  {
    open(FOO, $user_file) or croak "can't open $user_file";
    local $/;
    $user_rules = <FOO>;
    close FOO;
  }

  my $glass_rules = <<"END";
//==============================================================================
// Glasses in ${dir} from glass.list
//==============================================================================

END
  for my $c (@{$CATALOG->{ClassList}})
  {
    next unless $CATALOG->{Classes}{$c}{Stem} =~ m!^${dir}/!;
    $glass_rules .= "#pragma link C++ class gled::ZLink<gled::${c}>;\n";
    unless ($user_rules =~ m/^\s*\#pragma\s+link\s+C\+\+\s+class\s+gled::${c}\s*[-+!]*\s*;/m)
    {
      $glass_rules .= "#pragma link C++ class gled::${c}+;\n";
    }
  }

  $rules .= <<"END";
//==============================================================================
// ${user_file}
//==============================================================================

${user_rules}
${glass_rules}
END
}

my $linkdef = <<"END";
// Generated by gled_mk_dict_gen.pl; do not edit.

#ifdef __CINT__
#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;

#pragma link C++ nestedclass;
#pragma link C++ nestedtypedef;

${rules}
#endif
END

open(FOO, ">$dict/${libset}_LinkDef.h") or croak "can't write $dict/${libset}_LinkDef.h";
print FOO $linkdef;
close FOO;

#-------------------------------------------------------------------------------
# Module map
#-------------------------------------------------------------------------------

# A header included inside braces (.h7 files, Var1's Ice/*.h) is textual, and
# so is everything it includes.
my (%seen, %textual);
my @todo = map { [ $_, 0 ] } @hdrs;
while (my $x = shift @todo)
{
  my ($h, $in_scope) = @$x;
  $in_scope ||= ($h =~ m/\.h7$/);
  next if $seen{$h} and (not $in_scope or $textual{$h});
  $seen{$h} = 1;
  $textual{$h} = 1 if $in_scope;

  open(my $fh, '<', $h) or croak "can't open $h";
  my $depth = 0;
  my $in_comment = 0;
  while (my $l = <$fh>)
  {
    if (not $in_comment and $l =~ m/^\s*#\s*include\s*[<"]([^>"]+)[>"]/)
    {
      my $inc = $1;
      (my $here = $h) =~ s![^/]*$!!;
      my $f = -f $inc ? $inc : (-f "$here$inc" ? "$here$inc" : undef);
      push @todo, [ $f, $in_scope || $depth > 0 ] if defined $f;
      next;
    }
    next if $l =~ m/^\s*#/;
    # Drop comments and literals, then count the braces.
    if ($in_comment)
    {
      next unless $l =~ s!^.*?\*/!!;
      $in_comment = 0;
    }
    $l =~ s!"(\\.|[^"\\])*"!""!g;
    $l =~ s!'(\\.|[^'\\])*'!''!g;
    $l =~ s!/\*.*?\*/!!g;
    $l =~ s!//.*$!!;
    $in_comment = 1 if $l =~ s!/\*.*$!!;
    $depth += () = $l =~ m/\{/g;
    $depth -= () = $l =~ m/\}/g;
  }
  close $fh;
}
my @modular = grep { not $textual{$_} } keys %seen;
my @textual = keys %textual;

my $modulemap = "// Generated by gled_mk_dict_gen.pl; do not edit.\n\n" .
                "module \"${libset}\" {\n  requires cplusplus\n";
$modulemap .= "  module \"$_\" { header \"$_\" export * }\n" for sort @modular;
$modulemap .= "  textual header \"$_\"\n"                    for sort @textual;
$modulemap .= "  export *\n}\n";

open(FOO, ">module.modulemap") or croak "can't write module.modulemap";
print FOO $modulemap;
close FOO;

open(FOO, ">lib/module.modulemap") or croak "can't write lib/module.modulemap";
print FOO "// Generated by gled_mk_dict_gen.pl; do not edit.\n\n" .
          "extern module ${libset} \"../module.modulemap\"\n";
close FOO;

#-------------------------------------------------------------------------------
# rootcling
#-------------------------------------------------------------------------------

my $deps = "";
for my $d (@{$specs->{$libset}{Deps}})
{
  $deps .= " -m $d.pcm -moduleMapFile=$specs->{$d}{Dir}/module.modulemap";
}

my $exe = "$ENV{ROOTSYS}/bin/rootcling -f $dict/${libset}_Dict.cc " .
          "-s $ENV{GLEDSYS}/lib/lib${libset}.so -cxxmodule -writeEmptyRootPCM${deps} " .
          "-rmf lib/lib${libset}.rootmap -rml lib${libset}.so " .
          "-I. $ENV{CPPFLAGS} -I$ENV{ROOTSYS}/include " .
          join(" ", @hdrs) . " $dict/${libset}_LinkDef.h";
print $exe."\n";
my $ret = `$exe`;
croak $ret if $?;

system("mv -f $ENV{GLEDSYS}/lib/${libset}.pcm lib/${libset}.pcm") == 0
  or croak "can't move $ENV{GLEDSYS}/lib/${libset}.pcm to lib/";
