#!/usr/bin/perl

# Copyright (C) Matevz Tadel.
# This file is part of Gled.
# SPDX-License-Identifier: LGPL-3.0-or-later

use lib "$ENV{GLEDSYS}/perllib";
use Gled_ConfCat_Parser;

# Make-Dict-depend
##################
# Input: libset name, then the header files that are to be rootcling-ed
# Output: make dependencies for generation of the dictionaries,
#         usually stored in make_dict.inc
#
# Headers are grouped by directory. A directory gets the dictionary
# <libset>_<dir>_Dict when it holds glasses or a LinkDef.h, and one more,
# <libset>_<dir>_<tag>_Dict, for each <dir>/LinkDef_<tag>.h. Each dictionary is
# generated from all the headers of its directory. The same selection is
# made in make_base.inc for DICT_AUTO_BASE.

# read build config
Gled_ConfCat_Parser::import_build_config();
Gled_ConfCat_Parser::parse_catalog();

$libset = shift;

print "# Generated by gled_mk_dict_dep.pl for libset $libset; do not edit. Make\n" .
      "# rewrites it when glass.list, a LinkDef*.h or the Makefile changes.\n\n";

for $h (@ARGV) {
  ($d) = $h =~ m!^(\w+)/! or die "header '$h' not in a directory";
  push @{$dir_hdrs{$d}}, $h;
}
for $c (@{$CATALOG->{ClassList}}) {
  ($d) = $CATALOG->{Classes}{$c}{Stem} =~ m!^(\w+)/!;
  $glass_dirs{$d} = 1;
}

for $d (sort keys %dir_hdrs) {
  @dicts = ();
  if ($glass_dirs{$d} or -r "$d/LinkDef.h") {
    push @dicts, [ "${libset}_${d}_Dict", "", "\$(wildcard $d/LinkDef.h)" .
                   ($glass_dirs{$d} ? " glass.list" : "") ];
  }
  for $ld (sort glob("$d/LinkDef_*.h")) {
    ($tag) = $ld =~ m!/LinkDef_(\w+)\.h$! or next;
    push @dicts, [ "${libset}_${d}_${tag}_Dict", "-t $tag ", $ld ];
  }
  die "$libset: dictionary headers in $d/, but no glasses and no $d/LinkDef.h\n"
    unless @dicts;

  $hdrs = join(" ", @{$dir_hdrs{$d}});
  for $x (@dicts) {
    ($name, $opt, $deps) = @$x;
    $dbase = "$config->{DICT_DIR}/$name";
    print "$dbase.d: $hdrs\n";
    print "\t\${ECHO} -d- Mk-dict-depend $name\n";
    print "\t\${MUTE} \${MKDEP} \${MKDEPFLAGS} -- \${LOCALINCL} -- \$^ -f- 2>/dev/null | " .
              "sed -e 's!^[^ :]*\\.o:!$dbase.cc:!' > \$\@\n";
    print "$dbase.cc: $hdrs $deps\n";
    print "\t\${ECHO} -=- Rootcling $name\n";
    print "\t\${MUTE} (CPPFLAGS=\"\${CPPFLAGS}\" \${MKDICTGEN} $libset $d $opt$hdrs)\n";
  }
}
