#!/usr/bin/perl

# Copyright (C) Matevz Tadel.
# This file is part of Gled.
# SPDX-License-Identifier: LGPL-3.0-or-later

# Writes the manifest of a libset to stdout: what a build of other libsets
# needs to know about this one without running its Makefile. Run from the
# libset directory with the libsets it requires as arguments (the
# REQUIRES_LIB_SETS of its Makefile); the rest comes from build_config and
# glass.list. The directory of the libset is the one configure recorded.
#
# The manifest is a list of records. The struct lines name the fields; a
# trailing '@field' takes the remaining positional values, a trailing
# '%field' the 'key=value' ones. A glass with its own renderer gets
# 'rnr=<renderer class>'; without it, it uses the renderer of its parent.

use lib "$ENV{GLEDSYS}/perllib";
use Gled_ConfCat_Parser;
use Cwd qw(getcwd);

Gled_ConfCat_Parser::import_build_config();
Gled_ConfCat_Parser::parse_catalog();

my @deps = @ARGV;

sub val
{
  # Values that are not plain words or paths are quoted.
  my $v = shift;
  return $v if $v =~ m!^[\w./:+-]+$!;
  $v =~ s/(["\\])/\\$1/g;
  return "\"$v\"";
}

sub rec
{
  # rec(name, [positional values], [key => value, ...])
  my ($name, $pos, $named) = @_;
  my @args = map { val($_) } @$pos;
  my @kv   = @{$named || []};
  while (my ($k, $v) = splice(@kv, 0, 2))
  {
    push @args, "$k=" . val($v);
  }
  return "$name(" . join(', ', @args) . ")\n";
}

my $name = $CATALOG->{LibSetName};
my $dir  = $resolver->{LibName2LibSpecs}{$name}{Dir};
$dir = getcwd() unless defined $dir;

print "# Generated by gled_manifest_writer.pl for libset $name from its Makefile,\n";
print "# glass.list and build_config; do not edit.\n\n";

print "struct libset { name, id, dir, \@requires }\n";
print "struct glass  { name, class_id, stem, %opts }\n\n";

print rec('libset', [$name, $CATALOG->{LibID}, $dir, @deps]);
print "\n";

for my $c (@{$CATALOG->{ClassList}})
{
  my $g = $CATALOG->{Classes}{$c};
  my @opts = $g->{RnrClass} ne "" ? (rnr => $g->{RnrClass}) : ();
  print rec('glass', [$c, $g->{ClassID}, $g->{Stem}], \@opts);
}
