#!/usr/bin/perl

# Copyright (C) Matevz Tadel.
# This file is part of Gled.
# SPDX-License-Identifier: LGPL-3.0-or-later

# Writes the manifest of a libset to stdout, for builds against this area.
# Usage, in the libset directory: gled_manifest_writer.pl <required libsets>

use lib "$ENV{GLEDSYS}/perllib";
use Gled_ConfCat_Parser;
use Cwd qw(getcwd);

Gled_ConfCat_Parser::import_build_config();
Gled_ConfCat_Parser::parse_catalog();

my @deps = @ARGV;

sub val
{
  # Values that are not plain words or paths are quoted.
  my $v = shift;
  return $v if $v =~ m!^[\w./:+-]+$!;
  $v =~ s/(["\\])/\\$1/g;
  return "\"$v\"";
}

sub rec
{
  # rec(name, [positional values], [key => value, ...])
  my ($name, $pos, $named) = @_;
  my @args = map { val($_) } @$pos;
  my @kv   = @{$named || []};
  while (my ($k, $v) = splice(@kv, 0, 2))
  {
    push @args, "$k=" . val($v);
  }
  return "$name(" . join(', ', @args) . ")\n";
}

my $name = $CATALOG->{LibSetName};
my $dir  = $resolver->{LibName2LibSpecs}{$name}{Dir};
$dir = getcwd() unless defined $dir;

print "# Generated by gled_manifest_writer.pl for libset $name from its Makefile,\n";
print "# glass.list and build_config; do not edit.\n\n";

print "struct libset { name, id, dir, \@requires }\n";
print "struct glass  { name, class_id, stem, %opts }\n\n";

print rec('libset', [$name, $CATALOG->{LibID}, $dir, @deps]);
print "\n";

for my $c (@{$CATALOG->{ClassList}})
{
  my $g = $CATALOG->{Classes}{$c};
  my @opts = $g->{RnrClass} ne "" ? (rnr => $g->{RnrClass}) : ();
  print rec('glass', [$c, $g->{ClassID}, $g->{Stem}], \@opts);
}
