#!/usr/bin/perl

# Copyright (C) Matevz Tadel.
# This file is part of Gled.
# SPDX-License-Identifier: LGPL-3.0-or-later

# Generates the ROOT dictionary of one directory of a libset with a single
# rootcling run.
#
# Usage: gled_mk_dict_gen.pl <libsetname> <dir> <headers ...>
#
# Writes dict/<libsetname>_<dir>_LinkDef.h and runs rootcling over the
# headers, producing dict/<libsetname>_<dir>_Dict.cc and
# dict/<libsetname>_<dir>_Dict_rdict.pcm. The selection rules come from two
# places:
# - Every glass in glass.list that lives in <dir> gets 'class gled::<Glass>+'
#   and 'class gled::ZLink<gled::<Glass>>'. The first one is skipped when
#   <dir>/LinkDef.h names the glass itself, e.g. as 'gled::AList-'.
# - <dir>/LinkDef.h, if it exists, is copied in verbatim. It lists all the
#   other classes, namespaces, typedefs, functions and globals.

use lib "$ENV{GLEDSYS}/perllib";
use Carp;
use Gled_ConfCat_Parser;

Gled_ConfCat_Parser::import_build_config();
Gled_ConfCat_Parser::parse_catalog();

my $libset = shift;
my $dir    = shift;
my @hdrs   = @ARGV;
my $dict   = $config->{DICT_DIR};

my $user_file = "${dir}/LinkDef.h";
my $stem      = "${libset}_${dir}";

my $user_rules = "";
if (-r $user_file)
{
  open(FOO, $user_file) or croak "can't open $user_file";
  local $/;
  $user_rules = <FOO>;
  close FOO;
}

my $glass_rules = <<"END";
//==============================================================================
// Glasses in ${dir} from glass.list
//==============================================================================

END
for my $c (@{$CATALOG->{ClassList}})
{
  next unless $CATALOG->{Classes}{$c}{Stem} =~ m!^${dir}/!;
  $glass_rules .= "#pragma link C++ class gled::ZLink<gled::${c}>;\n";
  unless ($user_rules =~ m/^\s*\#pragma\s+link\s+C\+\+\s+class\s+gled::${c}\s*[-+!]*\s*;/m)
  {
    $glass_rules .= "#pragma link C++ class gled::${c}+;\n";
  }
}

my $linkdef = <<"END";
// Generated by gled_mk_dict_gen.pl; do not edit.

#ifdef __CINT__
#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;

#pragma link C++ nestedclass;
#pragma link C++ nestedtypedef;

//==============================================================================
// ${user_file}
//==============================================================================

${user_rules}
${glass_rules}
#endif
END

open(FOO, ">$dict/${stem}_LinkDef.h") or croak "can't write $dict/${stem}_LinkDef.h";
print FOO $linkdef;
close FOO;

my $exe = "$ENV{ROOTSYS}/bin/rootcling -f $dict/${stem}_Dict.cc " .
          "-I. $ENV{CPPFLAGS} -I$ENV{ROOTSYS}/include " .
          join(" ", @hdrs) . " $dict/${stem}_LinkDef.h";
print $exe."\n";
my $ret = `$exe`;
croak $ret if $?;
